vehicles:
	go run ./cmd/csvimporter/ data.csv vehicles ";"
customers:
	go run ./cmd/csvimporter/ customers.csv customers ","
switch-sqlite:
	cp .env.sqlite.example .env.csvimporter
switch-mysql:
	cp .env.mysql.example .env.csvimporter
switch-pgsql:
	cp .env.pgsql.example .env.csvimporter
switch-firebird:
	cp .env.firebird.example .env.csvimporter
lint:
	gocritic check ./...
	revive ./...
	golint ./...
	go vet ./...
	staticcheck ./...
	# golangci-lint run
	goconst ./...
test:
	go test ./...
